# Algorytmika i matematyka uczenia maszynowego 
## Laboratorium 4

Do wykonania laboratorium należy skorzystać z bibliotek:
- [numpy](https://numpy.org/)
- [matplotlib](https://matplotlib.org/)

### Zadanie 1

Dana jest następująca lista prostokątów:

```
rectangles = [("R1", 5, 4.5), ("Szeroki", 11, 3), ("R2", 4, 6), ("Wąski", 3, 8), ("Kwadrat 1", 5, 5), ("Kwadrat 2", 4.5, 4.5)] 
```

gdzie kolejne pola krotek to: 
- nazwa, 
- szerokość, 
- wysokość.

#### A) 
Na jej bazie utwórz ustrukturalizowaną tablicę Numpy (`np.array(...)`), następnie posortuj dane prostokąty rosnąco po polu, a w przypadku równości niech decyduje (alfabetycznie) nazwa prostokąta.

#### B) 
Wypisz posortowaną tablicę, w kolejności pól: 
1. szerokość, 
2. wysokość, 
3. nazwa.

> Uwaga: Gdzie to możliwe, działaj na typach i funkcjach z biblioteki Numpy.



In [3]:
import numpy as np

rectangles = [("R1", 5, 4.5), ("Szeroki", 11, 3), ("R2", 4, 6), ("Wąski", 3, 8), ("Kwadrat 1", 5, 5), ("Kwadrat 2", 4.5, 4.5)]

rectangles_new = list()
for i in rectangles:
    field = i[1] * i[2]
    i = i + (field,)
    rectangles_new.append(i)

dtype_rectangles = [('name', 'U32'), ('width', float), ('height', float),('field', float)]
np_rectangles = np.array(rectangles_new, dtype=dtype_rectangles)

np_rectangles = np.sort(np_rectangles, order=['field', 'name']) 
np_rectangles

array([('Kwadrat 2',  4.5, 4.5, 20.25), ('R1',  5. , 4.5, 22.5 ),
       ('R2',  4. , 6. , 24.  ), ('Wąski',  3. , 8. , 24.  ),
       ('Kwadrat 1',  5. , 5. , 25.  ), ('Szeroki', 11. , 3. , 33.  )],
      dtype=[('name', '<U32'), ('width', '<f8'), ('height', '<f8'), ('field', '<f8')])

In [2]:
for row in np_rectangles:
    print(65*'-')
    print(f'{row[1]:^22}|{row[2]:^20}|{row[0]:^20}')  

-----------------------------------------------------------------
         4.5          |        4.5         |     Kwadrat 2      
-----------------------------------------------------------------
         5.0          |        4.5         |         R1         
-----------------------------------------------------------------
         4.0          |        6.0         |         R2         
-----------------------------------------------------------------
         3.0          |        8.0         |       Wąski        
-----------------------------------------------------------------
         5.0          |        5.0         |     Kwadrat 1      
-----------------------------------------------------------------
         11.0         |        3.0         |      Szeroki       


### Zadanie 2 - gra 2048

Dana jest kwadratowa plansza o boku `SIZE` (np. 4) dla znanej gry 2048 (https://2048game.com/pl/). 
Każdy wiersz zawiera od 0 do 4 liczb. Należy, z wykorzystaniem konstrukcji Numpy, zasymulować ruch w lewo, w prawo, w górę i w dół planszy zgodnie z regułami gry (ale **BEZ** dodawania nowego kafelka w losowym miejscu). Innymi słowy, trzeba napisać cztery funkcje: 
- `move_left(...)`, 
- `move_right(...)`, 
- `move_up(...)`, 
- `move_down(...)`.

Przykład ruchu w prawo:

Wejściem i wyjściem każdej z obu funkcji jest 2-wymiarowa tablica Numpy.

> UWAGA: postaraj się napisać funkcję tylko do jednego ruchu, a pozostałe trzy niech się do niej w sprytny sposób odwołują.

In [43]:
def sum_row(row, count):
    row = row[row !=0]
    row_to_insert = np.zeros(count)
    for i in range(len(row)):
         if i < (len(row) -1):
            if row[i] == row[i+1]:
                row[i] *= 2
                row = np.delete(row, i+1)
    
    for i in range(len(row)):
        row_to_insert[i] = row[i]
    return row_to_insert

def move_left(matrix):
    for i in range(len(matrix)):
        matrix[i] = sum_row(matrix[i],len(matrix[i]))
    return matrix

def move_right(matrix):
    matrix = move_left(np.rot90(matrix, 2))
    return np.rot90(matrix, 2, axes=(0, 1))
    
def move_up(matrix):
    matrix = move_left(np.rot90(matrix, 1))
    return np.rot90(matrix, 3, axes=(0, 1))

def move_down(matrix):
    matrix = move_left(np.rot90(matrix, 3))
    return np.rot90(matrix, 1, axes=(0, 1))          

In [44]:
matrix = np.array([[2,2,2,4,4],
                   [2,4,4,0,4],
                   [0,4,2,0,4],
                   [0,4,0,2,4],
                   [0,4,0,0,4]])
matrix = move_down(matrix)
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 2 2 0 4]
 [0 8 4 4 8]
 [4 8 2 2 8]]
